import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';

import '../../../core/theme/trombl_theme.dart';
import '../../../core/observability/analytics_service.dart';
import '../../../shared/models/models.dart';
import '../../menu/domain/action_engine.dart';
import '../../menu/domain/menu_models.dart';
import '../../plan/presentation/create_plan_screen.dart';
import '../providers/reaction_provider.dart';

/// Passed via GoRouter's `extra` parameter.
class ResponseArgs {
  const ResponseArgs({
    required this.pick,
    required this.vibe,
    required this.optionLabel,
    required this.tag,         // string tag: "squad"|"discover"|"order in"|"rest"|"content"|"coming soon"
    this.tromMessage,          // squad WhatsApp draft (pre-generated by options sheet)
  });
  final Pick pick;
  final String vibe;
  final String optionLabel;
  final String tag;
  final String? tromMessage;
}

class ResponseScreen extends ConsumerWidget {
  const ResponseScreen({super.key, required this.args});
  final ResponseArgs args;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final accent   = TromblColors.accentFor(args.vibe);
    final reaction = ref.watch(reactionProvider(
      (vibe: args.vibe, optionLabel: args.optionLabel),
    ));
    final def = ActionEngine.definitionFor(args.tag);

    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 18),
              GestureDetector(
                onTap: () {
                  HapticFeedback.lightImpact();
                  context.go('/menu');
                },
                child: const Text(
                  '← back',
                  style: TextStyle(
                    color: TromblColors.textMuted,
                    fontSize: 13,
                    fontFamily: TromblText.sans,
                  ),
                ),
              ),

              // Scrollable reaction
              Expanded(
                child: SingleChildScrollView(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(vertical: 36),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Option tag chip
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 9, vertical: 4),
                          decoration: BoxDecoration(
                            color: accent.withValues(alpha: 0.10),
                            borderRadius: BorderRadius.circular(20),
                            border: Border.all(
                                color: accent.withValues(alpha: 0.25)),
                          ),
                          child: Text(
                            args.optionLabel,
                            style: TextStyle(
                              color: accent,
                              fontSize: 11,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 0.3,
                              fontFamily: TromblText.sans,
                            ),
                          ),
                        ),
                        const SizedBox(height: 20),

                        // LLM reaction
                        reaction.when(
                          loading: () => const _TypingIndicator(),
                          error: (_, __) => GestureDetector(
                            onTap: () {
                              HapticFeedback.lightImpact();
                              ref.invalidate(reactionProvider((
                                vibe: args.vibe,
                                optionLabel: args.optionLabel,
                              )));
                            },
                            child: const Text(
                              "trom went quiet.\ntap to try again.",
                              style: TextStyle(
                                fontFamily: TromblText.serif,
                                fontSize: 28,
                                color: TromblColors.textMuted,
                                height: 1.25,
                                letterSpacing: -0.3,
                              ),
                            ),
                          ),
                          data: (text) => Text(
                            text,
                            style: const TextStyle(
                              fontFamily: TromblText.serif,
                              fontSize: 28,
                              color: TromblColors.text,
                              height: 1.25,
                              letterSpacing: -0.3,
                            ),
                          ),
                        ),

                        // Action card — "TROM'S TAKE" section
                        if (def != null) ...[
                          const SizedBox(height: 28),
                          _ActionCard(def: def),
                        ],
                      ],
                    ),
                  ),
                ),
              ),

              // ── Pinned CTAs ────────────────────────────────────────────────
              Column(
                children: [
                  // Primary action button
                  if (def != null) ...[
                    _ActionButton(
                      def: def,
                      onTap: () async {
                        HapticFeedback.mediumImpact();
                        final option = MenuOption(
                          id: args.pick.optionId,
                          label: args.optionLabel,
                          tag: args.tag,
                        );
                        final result = await ActionEngine.execute(
                          option: option,
                          vibe: args.vibe,
                          tromMessage: args.tromMessage,
                        );
                        AnalyticsService.actionLaunched(
                          tag: args.tag,
                          result: result.name,
                        );
                        if (!context.mounted) return;
                        switch (result) {
                          case ActionResult.dndInternal:
                            AnalyticsService.dndEntered();
                            context.push('/dnd');
                          case ActionResult.comingSoon:
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text("trom's still cooking this one. soon."),
                                behavior: SnackBarBehavior.floating,
                              ),
                            );
                          case ActionResult.failed:
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text("something went sideways. try again?"),
                                behavior: SnackBarBehavior.floating,
                              ),
                            );
                          case ActionResult.launched:
                            // For squad tag — after WhatsApp launches, offer to
                            // store the plan and share the link too.
                            if (args.tag == 'squad' && context.mounted) {
                              final reactionText = reaction.valueOrNull;
                              context.push('/create-plan',
                                  extra: CreatePlanArgs(
                                    vibe: args.vibe,
                                    optionLabel: args.optionLabel,
                                    reactionText: reactionText,
                                  ));
                            }
                        }
                      },
                    ),
                    const SizedBox(height: 10),
                  ],

                  // "make it a plan" shortcut for squad picks
                  if (args.tag == 'squad')
                    reaction.maybeWhen(
                      data: (text) => Padding(
                        padding: const EdgeInsets.only(bottom: 10),
                        child: _SecondaryButton(
                          label: 'make it a plan 🤙',
                          onTap: () {
                            HapticFeedback.lightImpact();
                            context.push('/create-plan',
                                extra: CreatePlanArgs(
                                  vibe: args.vibe,
                                  optionLabel: args.optionLabel,
                                  reactionText: text,
                                ));
                          },
                        ),
                      ),
                      orElse: () => const SizedBox.shrink(),
                    ),

                  // Share reaction
                  reaction.maybeWhen(
                    data: (text) => _SecondaryButton(
                      label: 'share this 🔗',
                      onTap: () {
                        HapticFeedback.lightImpact();
                        Share.share(
                          '${args.optionLabel}\n\n$text\n\n— trombl',
                          subject: args.optionLabel,
                        );
                      },
                    ),
                    orElse: () => const SizedBox.shrink(),
                  ),
                  const SizedBox(height: 10),
                  _SecondaryButton(
                    label: 'pick something else',
                    onTap: () => context.go('/menu'),
                  ),
                  const SizedBox(height: 16),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ─── Action card ─────────────────────────────────────────────────────────────

class _ActionCard extends StatelessWidget {
  const _ActionCard({required this.def});
  final ActionDefinition def;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: TromblColors.cardLit,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: def.color.withValues(alpha: 0.15)),
      ),
      child: Row(
        children: [
          Container(
            width: 44, height: 44,
            decoration: BoxDecoration(
              color: def.color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: def.color.withValues(alpha: 0.2)),
            ),
            child: Center(
              child: Text(def.icon, style: const TextStyle(fontSize: 20)),
            ),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  def.label,
                  style: const TextStyle(
                    color: TromblColors.text,
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                    fontFamily: TromblText.sans,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  def.description,
                  style: const TextStyle(
                    color: TromblColors.textSub,
                    fontSize: 12,
                    fontFamily: TromblText.sans,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Action button ────────────────────────────────────────────────────────────

class _ActionButton extends StatelessWidget {
  const _ActionButton({required this.def, required this.onTap});
  final ActionDefinition def;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 17),
        decoration: BoxDecoration(
          color: def.color,
          borderRadius: BorderRadius.circular(16),
        ),
        child: Text(
          def.cta,
          textAlign: TextAlign.center,
          style: const TextStyle(
            color: Color(0xFF090909),
            fontWeight: FontWeight.w800,
            fontSize: 15,
            fontFamily: TromblText.sans,
          ),
        ),
      ),
    );
  }
}

// ─── Secondary button ─────────────────────────────────────────────────────────

class _SecondaryButton extends StatelessWidget {
  const _SecondaryButton({required this.label, required this.onTap});
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 15),
        decoration: BoxDecoration(
          color: TromblColors.card,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: TromblColors.border),
        ),
        child: Text(
          label,
          textAlign: TextAlign.center,
          style: const TextStyle(
            color: TromblColors.textSub,
            fontWeight: FontWeight.w600,
            fontSize: 14,
            fontFamily: TromblText.sans,
          ),
        ),
      ),
    );
  }
}

// ─── Typing indicator ─────────────────────────────────────────────────────────

class _TypingIndicator extends StatefulWidget {
  const _TypingIndicator();

  @override
  State<_TypingIndicator> createState() => _TypingIndicatorState();
}

class _TypingIndicatorState extends State<_TypingIndicator>
    with SingleTickerProviderStateMixin {
  late AnimationController _ctrl;
  late Animation<double> _anim;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 900))
      ..repeat(reverse: true);
    _anim = Tween(begin: 0.3, end: 1.0).animate(
      CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut),
    );
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _anim,
      builder: (_, __) => Opacity(
        opacity: _anim.value,
        child: const Text(
          'trom is thinking...',
          style: TextStyle(
            fontFamily: TromblText.serif,
            fontSize: 28,
            color: TromblColors.textMuted,
            height: 1.25,
            letterSpacing: -0.3,
          ),
        ),
      ),
    );
  }
}
